<?php

namespace MasDistribucion\DefaultDb\Proxies\__CG__;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class DefaultDb_Entities_Product extends \DefaultDb_Entities_Product implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function setImages($images)
    {
        $this->__load();
        return parent::setImages($images);
    }

    public function getVariants()
    {
        $this->__load();
        return parent::getVariants();
    }

    public function getImages()
    {
        $this->__load();
        return parent::getImages();
    }

    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function getClient()
    {
        $this->__load();
        return parent::getClient();
    }

    public function getCatalog()
    {
        $this->__load();
        return parent::getCatalog();
    }

    public function getName()
    {
        $this->__load();
        return parent::getName();
    }

    public function getDescription()
    {
        $this->__load();
        return parent::getDescription();
    }

    public function getPrice()
    {
        $this->__load();
        return parent::getPrice();
    }

    public function getPriceList()
    {
        $this->__load();
        return parent::getPriceList();
    }

    public function getPriceCreditos()
    {
        $this->__load();
        return parent::getPriceCreditos();
    }

    public function getStock()
    {
        $this->__load();
        return parent::getStock();
    }

    public function getProvitionTime()
    {
        $this->__load();
        return parent::getProvitionTime();
    }

    public function getMaker()
    {
        $this->__load();
        return parent::getMaker();
    }

    public function getSku()
    {
        $this->__load();
        return parent::getSku();
    }

    public function getWarranty()
    {
        $this->__load();
        return parent::getWarranty();
    }

    public function getWeight()
    {
        $this->__load();
        return parent::getWeight();
    }

    public function getWidth()
    {
        $this->__load();
        return parent::getWidth();
    }

    public function getHeight()
    {
        $this->__load();
        return parent::getHeight();
    }

    public function getDepth()
    {
        $this->__load();
        return parent::getDepth();
    }

    public function getColor()
    {
        $this->__load();
        return parent::getColor();
    }

    public function getSize()
    {
        $this->__load();
        return parent::getSize();
    }

    public function getOffer()
    {
        $this->__load();
        return parent::getOffer();
    }

    public function getStatus()
    {
        $this->__load();
        return parent::getStatus();
    }

    public function getVariantsUse()
    {
        $this->__load();
        return parent::getVariantsUse();
    }

    public function getVisible()
    {
        $this->__load();
        return parent::getVisible();
    }

    public function getNewStartDate()
    {
        $this->__load();
        return parent::getNewStartDate();
    }

    public function getNewEndDate()
    {
        $this->__load();
        return parent::getNewEndDate();
    }

    public function getOrder()
    {
        $this->__load();
        return parent::getOrder();
    }

    public function getFeatured()
    {
        $this->__load();
        return parent::getFeatured();
    }

    public function setId($id)
    {
        $this->__load();
        return parent::setId($id);
    }

    public function setClient($client)
    {
        $this->__load();
        return parent::setClient($client);
    }

    public function setCatalog($catalog)
    {
        $this->__load();
        return parent::setCatalog($catalog);
    }

    public function setName($name)
    {
        $this->__load();
        return parent::setName($name);
    }

    public function setDescription($description)
    {
        $this->__load();
        return parent::setDescription($description);
    }

    public function setPrice($price)
    {
        $this->__load();
        return parent::setPrice($price);
    }

    public function setPriceCreditos($priceCreditos)
    {
        $this->__load();
        return parent::setPriceCreditos($priceCreditos);
    }

    public function setPriceList($priceList)
    {
        $this->__load();
        return parent::setPriceList($priceList);
    }

    public function setStock($stock)
    {
        $this->__load();
        return parent::setStock($stock);
    }

    public function setProvitionTime($provitionTime)
    {
        $this->__load();
        return parent::setProvitionTime($provitionTime);
    }

    public function setMaker($maker)
    {
        $this->__load();
        return parent::setMaker($maker);
    }

    public function setSku($sku)
    {
        $this->__load();
        return parent::setSku($sku);
    }

    public function setWarranty($warranty)
    {
        $this->__load();
        return parent::setWarranty($warranty);
    }

    public function setWeight($weight)
    {
        $this->__load();
        return parent::setWeight($weight);
    }

    public function setWidth($width)
    {
        $this->__load();
        return parent::setWidth($width);
    }

    public function setHeight($height)
    {
        $this->__load();
        return parent::setHeight($height);
    }

    public function setDepth($depth)
    {
        $this->__load();
        return parent::setDepth($depth);
    }

    public function setColor($color)
    {
        $this->__load();
        return parent::setColor($color);
    }

    public function setSize($size)
    {
        $this->__load();
        return parent::setSize($size);
    }

    public function setOffer($offer)
    {
        $this->__load();
        return parent::setOffer($offer);
    }

    public function setStatus($status)
    {
        $this->__load();
        return parent::setStatus($status);
    }

    public function setVariantsUse($variantsUse)
    {
        $this->__load();
        return parent::setVariantsUse($variantsUse);
    }

    public function setVisible($visible)
    {
        $this->__load();
        return parent::setVisible($visible);
    }

    public function setNewStartDate($newStartDate)
    {
        $this->__load();
        return parent::setNewStartDate($newStartDate);
    }

    public function setNewEndDate($newEndDate)
    {
        $this->__load();
        return parent::setNewEndDate($newEndDate);
    }

    public function setOrder($order)
    {
        $this->__load();
        return parent::setOrder($order);
    }

    public function setFeatured($featured)
    {
        $this->__load();
        return parent::setFeatured($featured);
    }

    public function setVariants($variants)
    {
        $this->__load();
        return parent::setVariants($variants);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'name', 'description', 'price', 'priceList', 'priceCreditos', 'stock', 'provitionTime', 'maker', 'sku', 'warranty', 'weight', 'width', 'height', 'depth', 'color', 'size', 'offer', 'status', 'variantsUse', 'visible', 'newStartDate', 'newEndDate', 'order', 'featured', 'client', 'catalog', 'images', 'variants');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}