<?php

namespace MasDistribucion\DefaultDb\Proxies\__CG__;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class DefaultDb_Entities_PackageToOrder extends \DefaultDb_Entities_PackageToOrder implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function getOrder()
    {
        $this->__load();
        return parent::getOrder();
    }

    public function getInvoice()
    {
        $this->__load();
        return parent::getInvoice();
    }

    public function getNumPackage()
    {
        $this->__load();
        return parent::getNumPackage();
    }

    public function getPrice()
    {
        $this->__load();
        return parent::getPrice();
    }

    public function getTotalPrice()
    {
        $this->__load();
        return parent::getTotalPrice();
    }

    public function getDateSend()
    {
        $this->__load();
        return parent::getDateSend();
    }

    public function getPackagingGenerated()
    {
        $this->__load();
        return parent::getPackagingGenerated();
    }

    public function getNamePackage()
    {
        $this->__load();
        return parent::getNamePackage();
    }

    public function getWeight()
    {
        $this->__load();
        return parent::getWeight();
    }

    public function getWidth()
    {
        $this->__load();
        return parent::getWidth();
    }

    public function getHeight()
    {
        $this->__load();
        return parent::getHeight();
    }

    public function getDepth()
    {
        $this->__load();
        return parent::getDepth();
    }

    public function getPackage()
    {
        $this->__load();
        return parent::getPackage();
    }

    public function getPromotion()
    {
        $this->__load();
        return parent::getPromotion();
    }

    public function setId($id)
    {
        $this->__load();
        return parent::setId($id);
    }

    public function setOrder($order)
    {
        $this->__load();
        return parent::setOrder($order);
    }

    public function setInvoice($invoice)
    {
        $this->__load();
        return parent::setInvoice($invoice);
    }

    public function setNumPackage($numPackage)
    {
        $this->__load();
        return parent::setNumPackage($numPackage);
    }

    public function setPrice($price)
    {
        $this->__load();
        return parent::setPrice($price);
    }

    public function setTotalPrice($totalPrice)
    {
        $this->__load();
        return parent::setTotalPrice($totalPrice);
    }

    public function setDateSend($dateSend)
    {
        $this->__load();
        return parent::setDateSend($dateSend);
    }

    public function setPackagingGenerated($packagingGenerated)
    {
        $this->__load();
        return parent::setPackagingGenerated($packagingGenerated);
    }

    public function setNamePackage($namePackage)
    {
        $this->__load();
        return parent::setNamePackage($namePackage);
    }

    public function setWeight($weight)
    {
        $this->__load();
        return parent::setWeight($weight);
    }

    public function setWidth($width)
    {
        $this->__load();
        return parent::setWidth($width);
    }

    public function setHeight($height)
    {
        $this->__load();
        return parent::setHeight($height);
    }

    public function setDepth($depth)
    {
        $this->__load();
        return parent::setDepth($depth);
    }

    public function setPackage($package)
    {
        $this->__load();
        return parent::setPackage($package);
    }

    public function setPromotion($promotion)
    {
        $this->__load();
        return parent::setPromotion($promotion);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'numPackage', 'price', 'totalPrice', 'dateSend', 'namePackage', 'weight', 'width', 'height', 'depth', 'order', 'invoice', 'packagingGenerated', 'package', 'promotion');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}