<?php

namespace MasDistribucion\DefaultDb\Proxies\__CG__;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class DefaultDb_Entities_Pagos extends \DefaultDb_Entities_Pagos implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function doStuffOnPrePersist()
    {
        $this->__load();
        return parent::doStuffOnPrePersist();
    }

    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function getUsuario()
    {
        $this->__load();
        return parent::getUsuario();
    }

    public function getCliente()
    {
        $this->__load();
        return parent::getCliente();
    }

    public function getOrden()
    {
        $this->__load();
        return parent::getOrden();
    }

    public function getMontoCompra()
    {
        $this->__load();
        return parent::getMontoCompra();
    }

    public function getMontoCreditos()
    {
        $this->__load();
        return parent::getMontoCreditos();
    }

    public function getFecha()
    {
        $this->__load();
        return parent::getFecha();
    }

    public function getEstatus()
    {
        $this->__load();
        return parent::getEstatus();
    }

    public function getTimestamp()
    {
        $this->__load();
        return parent::getTimestamp();
    }

    public function getCompraVenta()
    {
        $this->__load();
        return parent::getCompraVenta();
    }

    public function getCompraCreditos()
    {
        $this->__load();
        return parent::getCompraCreditos();
    }

    public function getPromocion()
    {
        $this->__load();
        return parent::getPromocion();
    }

    public function getTipoConcepto()
    {
        $this->__load();
        return parent::getTipoConcepto();
    }

    public function getTipoDebito()
    {
        $this->__load();
        return parent::getTipoDebito();
    }

    public function getDescripcion()
    {
        $this->__load();
        return parent::getDescripcion();
    }

    public function setId($id)
    {
        $this->__load();
        return parent::setId($id);
    }

    public function setUsuario($usuario)
    {
        $this->__load();
        return parent::setUsuario($usuario);
    }

    public function setCliente($cliente)
    {
        $this->__load();
        return parent::setCliente($cliente);
    }

    public function setOrden($orden)
    {
        $this->__load();
        return parent::setOrden($orden);
    }

    public function setMontoCompra($montoCompra)
    {
        $this->__load();
        return parent::setMontoCompra($montoCompra);
    }

    public function setMontoCreditos($montoCreditos)
    {
        $this->__load();
        return parent::setMontoCreditos($montoCreditos);
    }

    public function setFecha($fecha)
    {
        $this->__load();
        return parent::setFecha($fecha);
    }

    public function setEstatus($estatus)
    {
        $this->__load();
        return parent::setEstatus($estatus);
    }

    public function setTimestamp($timestamp)
    {
        $this->__load();
        return parent::setTimestamp($timestamp);
    }

    public function setCompraVenta($compraVenta)
    {
        $this->__load();
        return parent::setCompraVenta($compraVenta);
    }

    public function setCompraCreditos($compraCreditos)
    {
        $this->__load();
        return parent::setCompraCreditos($compraCreditos);
    }

    public function setPromocion($promocion)
    {
        $this->__load();
        return parent::setPromocion($promocion);
    }

    public function setTipoConcepto($tipoConcepto)
    {
        $this->__load();
        return parent::setTipoConcepto($tipoConcepto);
    }

    public function setTipoDebito($tipoDebito)
    {
        $this->__load();
        return parent::setTipoDebito($tipoDebito);
    }

    public function setDescripcion($descripcion)
    {
        $this->__load();
        return parent::setDescripcion($descripcion);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'orden', 'montoCompra', 'montoCreditos', 'fecha', 'estatus', 'timestamp', 'descripcion', 'usuario', 'cliente', 'compraVenta', 'compraCreditos', 'promocion', 'tipoConcepto', 'tipoDebito');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}