<?php

namespace MasDistribucion\DefaultDb\Proxies\__CG__;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class DefaultDb_Entities_User extends \DefaultDb_Entities_User implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getLink()
    {
        $this->__load();
        return parent::getLink();
    }

    public function setLink($linktoclients)
    {
        $this->__load();
        return parent::setLink($linktoclients);
    }

    public function getRegistration()
    {
        $this->__load();
        return parent::getRegistration();
    }

    public function setRegistration($registration)
    {
        $this->__load();
        return parent::setRegistration($registration);
    }

    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function getStatus()
    {
        $this->__load();
        return parent::getStatus();
    }

    public function getFirstName()
    {
        $this->__load();
        return parent::getFirstName();
    }

    public function getLastName()
    {
        $this->__load();
        return parent::getLastName();
    }

    public function getFullName()
    {
        $this->__load();
        return parent::getFullName();
    }

    public function getCode()
    {
        $this->__load();
        return parent::getCode();
    }

    public function setCode($code)
    {
        $this->__load();
        return parent::setCode($code);
    }

    public function getUsername()
    {
        $this->__load();
        return parent::getUsername();
    }

    public function getPassword()
    {
        $this->__load();
        return parent::getPassword();
    }

    public function getTitle()
    {
        $this->__load();
        return parent::getTitle();
    }

    public function getCommercialName()
    {
        $this->__load();
        return parent::getCommercialName();
    }

    public function getType()
    {
        $this->__load();
        return parent::getType();
    }

    public function getCellPhone()
    {
        $this->__load();
        return parent::getCellPhone();
    }

    public function getLocalNumber()
    {
        $this->__load();
        return parent::getLocalNumber();
    }

    public function getCategory()
    {
        $this->__load();
        return parent::getCategory();
    }

    public function getMoneda()
    {
        $this->__load();
        return parent::getMoneda();
    }

    public function getDayInvoice()
    {
        $this->__load();
        return parent::getDayInvoice();
    }

    public function getBranches()
    {
        $this->__load();
        return parent::getBranches();
    }

    public function getParent()
    {
        $this->__load();
        return parent::getParent();
    }

    public function getCredito()
    {
        $this->__load();
        return parent::getCredito();
    }

    public function getCreditoCongelado()
    {
        $this->__load();
        return parent::getCreditoCongelado();
    }

    public function getCreditoNegativo()
    {
        $this->__load();
        return parent::getCreditoNegativo();
    }

    public function getState()
    {
        $this->__load();
        return parent::getState();
    }

    public function getCountry()
    {
        $this->__load();
        return parent::getCountry();
    }

    public function getCity()
    {
        $this->__load();
        return parent::getCity();
    }

    public function setId($id)
    {
        $this->__load();
        return parent::setId($id);
    }

    public function setStatus($status)
    {
        $this->__load();
        return parent::setStatus($status);
    }

    public function setFirstName($firstName)
    {
        $this->__load();
        return parent::setFirstName($firstName);
    }

    public function setLastName($lastName)
    {
        $this->__load();
        return parent::setLastName($lastName);
    }

    public function setUsername($username)
    {
        $this->__load();
        return parent::setUsername($username);
    }

    public function setPassword($password)
    {
        $this->__load();
        return parent::setPassword($password);
    }

    public function setTitle($title)
    {
        $this->__load();
        return parent::setTitle($title);
    }

    public function setCommercialName($commercialName)
    {
        $this->__load();
        return parent::setCommercialName($commercialName);
    }

    public function setType($type)
    {
        $this->__load();
        return parent::setType($type);
    }

    public function setCellPhone($cellPhone)
    {
        $this->__load();
        return parent::setCellPhone($cellPhone);
    }

    public function setLocalNumber($localNumber)
    {
        $this->__load();
        return parent::setLocalNumber($localNumber);
    }

    public function setCategory($category)
    {
        $this->__load();
        return parent::setCategory($category);
    }

    public function setMoneda($moneda)
    {
        $this->__load();
        return parent::setMoneda($moneda);
    }

    public function setPoint($point)
    {
        $this->__load();
        return parent::setPoint($point);
    }

    public function setDayInvoice($dayInvoice)
    {
        $this->__load();
        return parent::setDayInvoice($dayInvoice);
    }

    public function setParent($parent)
    {
        $this->__load();
        return parent::setParent($parent);
    }

    public function getCatalogs()
    {
        $this->__load();
        return parent::getCatalogs();
    }

    public function getOrdersReceived()
    {
        $this->__load();
        return parent::getOrdersReceived();
    }

    public function getOrdersGenerated()
    {
        $this->__load();
        return parent::getOrdersGenerated();
    }

    public function setRole($role)
    {
        $this->__load();
        return parent::setRole($role);
    }

    public function getRole()
    {
        $this->__load();
        return parent::getRole();
    }

    public function setCredito($credito)
    {
        $this->__load();
        return parent::setCredito($credito);
    }

    public function setCreditoCongelado($creditoCongelado)
    {
        $this->__load();
        return parent::setCreditoCongelado($creditoCongelado);
    }

    public function setCreditoNegativo($creditoNegativo)
    {
        $this->__load();
        return parent::setCreditoNegativo($creditoNegativo);
    }

    public function setState($state)
    {
        $this->__load();
        return parent::setState($state);
    }

    public function setCountry($country)
    {
        $this->__load();
        return parent::setCountry($country);
    }

    public function setCity($city)
    {
        $this->__load();
        return parent::setCity($city);
    }

    public function getData()
    {
        $this->__load();
        return parent::getData();
    }

    public function getPoint()
    {
        $this->__load();
        return parent::getPoint();
    }

    public function getTypeString($type = false)
    {
        $this->__load();
        return parent::getTypeString($type);
    }

    public function getTerms()
    {
        $this->__load();
        return parent::getTerms();
    }

    public function getService()
    {
        $this->__load();
        return parent::getService();
    }

    public function getPrivacy()
    {
        $this->__load();
        return parent::getPrivacy();
    }

    public function setTerms($terms)
    {
        $this->__load();
        return parent::setTerms($terms);
    }

    public function setService($service)
    {
        $this->__load();
        return parent::setService($service);
    }

    public function setPrivacy($privacy)
    {
        $this->__load();
        return parent::setPrivacy($privacy);
    }

    public function getRfc()
    {
        $this->__load();
        return parent::getRfc();
    }

    public function setRfc($rfc)
    {
        $this->__load();
        return parent::setRfc($rfc);
    }

    public function getStreet()
    {
        $this->__load();
        return parent::getStreet();
    }

    public function setStreet($street)
    {
        $this->__load();
        return parent::setStreet($street);
    }

    public function getSuburb()
    {
        $this->__load();
        return parent::getSuburb();
    }

    public function setSuburb($suburb)
    {
        $this->__load();
        return parent::setSuburb($suburb);
    }

    public function getNumber()
    {
        $this->__load();
        return parent::getNumber();
    }

    public function setNumber($number)
    {
        $this->__load();
        return parent::setNumber($number);
    }

    public function getNumint()
    {
        $this->__load();
        return parent::getNumint();
    }

    public function setNumint($numint)
    {
        $this->__load();
        return parent::setNumint($numint);
    }

    public function getZip()
    {
        $this->__load();
        return parent::getZip();
    }

    public function setZip($zip)
    {
        $this->__load();
        return parent::setZip($zip);
    }

    public function getVisible()
    {
        $this->__load();
        return parent::getVisible();
    }

    public function setVisible($visible)
    {
        $this->__load();
        return parent::setVisible($visible);
    }

    public function getBank()
    {
        $this->__load();
        return parent::getBank();
    }

    public function setBank($bank)
    {
        $this->__load();
        return parent::setBank($bank);
    }

    public function getAccount()
    {
        $this->__load();
        return parent::getAccount();
    }

    public function setAccount($account)
    {
        $this->__load();
        return parent::setAccount($account);
    }

    public function getClabe()
    {
        $this->__load();
        return parent::getClabe();
    }

    public function setClabe($clabe)
    {
        $this->__load();
        return parent::setClabe($clabe);
    }

    public function getMail()
    {
        $this->__load();
        return parent::getMail();
    }

    public function setMail($mail)
    {
        $this->__load();
        return parent::setMail($mail);
    }

    public function getPhone()
    {
        $this->__load();
        return parent::getPhone();
    }

    public function setPhone($phone)
    {
        $this->__load();
        return parent::setPhone($phone);
    }

    public function getCrdPay()
    {
        $this->__load();
        return parent::getCrdPay();
    }

    public function setCrdPay($crdpay)
    {
        $this->__load();
        return parent::setCrdPay($crdpay);
    }

    public function getDelyPay()
    {
        $this->__load();
        return parent::getDelyPay();
    }

    public function setDelyPay($delypay)
    {
        $this->__load();
        return parent::setDelyPay($delypay);
    }

    public function getBusinessName()
    {
        $this->__load();
        return parent::getBusinessName();
    }

    public function setBusinessName($businessname)
    {
        $this->__load();
        return parent::setBusinessName($businessname);
    }

    public function getToken()
    {
        $this->__load();
        return parent::getToken();
    }

    public function setToken($token)
    {
        $this->__load();
        return parent::setToken($token);
    }

    public function getMsg()
    {
        $this->__load();
        return parent::getMsg();
    }

    public function setMsg($msgtoclients)
    {
        $this->__load();
        return parent::setMsg($msgtoclients);
    }

    public function getMsg2()
    {
        $this->__load();
        return parent::getMsg2();
    }

    public function setMsg2($msgtoclients2)
    {
        $this->__load();
        return parent::setMsg2($msgtoclients2);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'code', 'status', 'firstName', 'lastName', 'username', 'password', 'title', 'commercialName', 'cellPhone', 'localNumber', 'type', 'dayInvoice', 'credito', 'creditoCongelado', 'creditoNegativo', 'terms', 'service', 'privacy', 'rfc', 'street', 'suburb', 'number', 'numint', 'zip', 'visible', 'bank', 'account', 'clabe', 'mail', 'phone', 'crdpay', 'delypay', 'businessname', 'token', 'msgtoclients', 'msgtoclients2', 'registration', 'linktoclients', 'catalogs', 'ordersReceived', 'ordersGenerated', 'category', 'point', 'branches', 'parent', 'role', 'moneda', 'state', 'country', 'city');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}