<?php

namespace MasDistribucion\DefaultDb\Proxies\__CG__;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class DefaultDb_Entities_RoutePoint extends \DefaultDb_Entities_RoutePoint implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function getRoute()
    {
        $this->__load();
        return parent::getRoute();
    }

    public function getOrder()
    {
        $this->__load();
        return parent::getOrder();
    }

    public function getPoint()
    {
        $this->__load();
        return parent::getPoint();
    }

    public function getStatus()
    {
        $this->__load();
        return parent::getStatus();
    }

    public function getArrivalTime()
    {
        $this->__load();
        return parent::getArrivalTime();
    }

    public function getRequired()
    {
        $this->__load();
        return parent::getRequired();
    }

    public function setId($id)
    {
        $this->__load();
        return parent::setId($id);
    }

    public function setRoute($route)
    {
        $this->__load();
        return parent::setRoute($route);
    }

    public function setOrder($order)
    {
        $this->__load();
        return parent::setOrder($order);
    }

    public function setPoint($point)
    {
        $this->__load();
        return parent::setPoint($point);
    }

    public function setStatus($status)
    {
        $this->__load();
        return parent::setStatus($status);
    }

    public function setArrivalTime($arrivalTime)
    {
        $this->__load();
        return parent::setArrivalTime($arrivalTime);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'order', 'status', 'arrivalTime', 'required', 'route', 'point');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}