<?php

namespace MasDistribucion\DefaultDb\Proxies\__CG__;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class DefaultDb_Entities_ActividaChoferLog extends \DefaultDb_Entities_ActividaChoferLog implements \Doctrine\ORM\Proxy\Proxy {

    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;

    public function __construct($entityPersister, $identifier) {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }

    /** @private */
    public function __load() {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized() {
        return $this->__isInitialized__;
    }
    public function getId()
    {
        $this->__load();
        return parent::getId();
    }
    public function getFechaMov()
    {
        $this->__load();
        return parent::getFechaMov();
    }
    public function getTipoMovivimient()
    {
        $this->__load();
        return parent::getTipoMovivimient();
    }
    public function getMetodoPago()
    {
        $this->__load();
        return parent::getMetodoPago();
    }
     public function getReferencia()
    {
        $this->__load();
        return parent::getReferencia();
    }
    
     public function getConcepto()
    {
        $this->__load();
        return parent::getConcepto();
    }
    
    public function getEstatus()
    {
        $this->__load();
        return parent::getEstatus();
    }
    public function getValor()
    {
        $this->__load();
        return parent::getValor();
    }
     public function getSaldoCaja()
    {
        $this->__load();
    return parent::getSaldoCaja();
    }
    public function setId($id)
    {
        $this->__load();
        return parent::setId($id);
    }
    public function setFechaMov($fechaMov)
    {
        $this->__load();
        return parent::setFechaMov($fechaMov);
    }
     public function setTipoMovivimient($tipoMovivimient)
    {
        $this->__load();
        return parent::setTipoMovivimient($tipoMovivimient);
    }
      public function setMetodoPago($metodoPago)
    {
        $this->__load();
        return parent::setMetodoPago($metodoPago);
    }
       public function setReferencia($referencia)
    {
        $this->__load();
        return parent::setReferencia($referencia);
    }
       public function setConcepto($concepto)
    {
        $this->__load();
        return parent::setConcepto($concepto);
    }
        public function setEstatus($estatus)
    {
        $this->__load();
        return parent::setEstatus($estatus);
    }
       public function setValor($valor)
    {
        $this->__load();
        return parent::setValor($valor);
    }
        public function setSaldoCaja($saldoCaja)
    {
        $this->__load();
        return parent::setSaldoCaja($saldoCaja);
    }
    
    
}
