<?php

namespace MasDistribucion\DefaultDb\Proxies\__CG__;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class DefaultDb_Entities_AprobacionCreditoControlador extends \DefaultDb_Entities_CompraCreditos implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        $this->__load();
        return parent::getId();
    }

    public function getUsuario()
    {
        $this->__load();
        return parent::getUsuario();
    }
    
    public function getTipoPago()
    {
        $this->__load();
        return parent::getTipoPago();
    }
    
    public function getMontoCompra()
    {
        $this->__load();
        return parent::getMontoCompra();
    }
    
    public function getCreditos()
    {
        $this->__load();
        return parent::getCreditos();
    }
    
    public function getFecha()
    {
        $this->__load();
        return parent::getFecha();
    }
    
    public function getNombreImg()
    {
        $this->__load();
        return parent::getNombreImg();
    }
    
    public function getPath()
    {
        $this->__load();
        return parent::getPath();
    }
    
    public function getMoneda()
    {
        $this->__load();
        return parent::getMoneda();
    }
    
    public function getName()
    {
        $this->__load();
        return parent::getName();
    }
    
    public function getReferencia()
    {
        $this->__load();
        return parent::getReferencia();
    }
    
    public function getCuenta()
    {
        $this->__load();
        return parent::getCuenta();
    }
    
    public function getEstado()
    {
        $this->__load();
        return parent::getEstado();
    }
    
    public function getClient()
    {
        $this->__load();
        return parent::getClient();
    }

    public function setId($id)
    {
        $this->__load();
        return parent::setId($id);
    }

    public function setUsuario($usuario)
    {
        $this->__load();
        return parent::setUsuario($usuario);
    }
    
    public function setTipoPago($tipoPago)
    {
        $this->__load();
        return parent::setTipoPago($tipoPago);
    }
    
    public function setMontoCompra($montoCompra)
    {
        $this->__load();
        return parent::setMontoCompra($montoCompra);
    }
    
    public function setCreditos($creditos)
    {
        $this->__load();
        return parent::setCreditos($creditos);
    }
    
    public function setFecha($fecha)
    {
        $this->__load();
        return parent::setFecha($fecha);
    }
    
    public function setNombreImg($nombreImg)
    {
        $this->__load();
        return parent::setNombreImg($nombreImg);
    }
    
    public function setPath($path)
    {
        $this->__load();
        return parent::setPath($path);
    }
    
    public function setMoneda($moneda)
    {
        $this->__load();
        return parent::setMoneda($moneda);
    }
    
    public function setName($name)
    {
        $this->__load();
        return parent::setName($name);
    }
    
    public function setReferencia($referencia)
    {
        $this->__load();
        return parent::setReferencia($referencia);
    }
    
    public function setCuenta($cuenta)
    {
        $this->__load();
        return parent::setCuenta($cuenta);
    }
    
    public function setEstado($estado)
    {
        $this->__load();
        return parent::setEstado($estado);
    }
    
    public function setClient($client)
    {
        $this->__load();
        return parent::setClient($client);
    }
    
    
    


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'usuario','tipoPago', 'montoCompra', 'creditos', 'fecha', 'nombreImg', 'path', 'moneda', 'name', 'referencia', 'cuenta', 'estado','client');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}