<?php

namespace MasDistribucion\DefaultDb\Proxies\__CG__;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class DefaultDb_Entities_Point extends \DefaultDb_Entities_Point implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function getCountry()
    {
        $this->__load();
        return parent::getCountry();
    }

    public function getState()
    {
        $this->__load();
        return parent::getState();
    }

    public function getCity()
    {
        $this->__load();
        return parent::getCity();
    }

    public function getCode()
    {
        $this->__load();
        return parent::getCode();
    }

    public function getName()
    {
        $this->__load();
        return parent::getName();
    }

    public function getAddress()
    {
        $this->__load();
        return parent::getAddress();
    }

    public function getExtNumber()
    {
        $this->__load();
        return parent::getExtNumber();
    }

    public function getIntNumber()
    {
        $this->__load();
        return parent::getIntNumber();
    }

    public function getType()
    {
        $this->__load();
        return parent::getType();
    }

    public function getStatus()
    {
        $this->__load();
        return parent::getStatus();
    }

    public function getStatusString()
    {
        $this->__load();
        return parent::getStatusString();
    }

    public function getController()
    {
        $this->__load();
        return parent::getController();
    }

    public function getOpeningTime()
    {
        $this->__load();
        return parent::getOpeningTime();
    }

    public function getClosingTime()
    {
        $this->__load();
        return parent::getClosingTime();
    }

    public function getComments()
    {
        $this->__load();
        return parent::getComments();
    }

    public function getDeleted()
    {
        $this->__load();
        return parent::getDeleted();
    }

    public function getWebpage()
    {
        $this->__load();
        return parent::getWebpage();
    }

    public function getClassificationId()
    {
        $this->__load();
        return parent::getClassificationId();
    }

    public function getCategoryId()
    {
        $this->__load();
        return parent::getCategoryId();
    }

    public function getUrlGoogleMaps()
    {
        $this->__load();
        return parent::getUrlGoogleMaps();
    }

    public function getFullAddress()
    {
        $this->__load();
        return parent::getFullAddress();
    }

    public function setId($id)
    {
        $this->__load();
        return parent::setId($id);
    }

    public function setCountry($country)
    {
        $this->__load();
        return parent::setCountry($country);
    }

    public function setState($state)
    {
        $this->__load();
        return parent::setState($state);
    }

    public function setCity($city)
    {
        $this->__load();
        return parent::setCity($city);
    }

    public function setCode($code)
    {
        $this->__load();
        return parent::setCode($code);
    }

    public function setName($name)
    {
        $this->__load();
        return parent::setName($name);
    }

    public function setAddress($address)
    {
        $this->__load();
        return parent::setAddress($address);
    }

    public function setExtNumber($extNumber)
    {
        $this->__load();
        return parent::setExtNumber($extNumber);
    }

    public function setIntNumber($extNumber)
    {
        $this->__load();
        return parent::setIntNumber($extNumber);
    }

    public function setType($type)
    {
        $this->__load();
        return parent::setType($type);
    }

    public function setStatus($status)
    {
        $this->__load();
        return parent::setStatus($status);
    }

    public function setController($controller)
    {
        $this->__load();
        return parent::setController($controller);
    }

    public function setOpeningTime($openingTime)
    {
        $this->__load();
        return parent::setOpeningTime($openingTime);
    }

    public function setClosingTime($closingTime)
    {
        $this->__load();
        return parent::setClosingTime($closingTime);
    }

    public function setComments($comments)
    {
        $this->__load();
        return parent::setComments($comments);
    }

    public function setDeleted($deleted)
    {
        $this->__load();
        return parent::setDeleted($deleted);
    }

    public function setWebpage($webpage)
    {
        $this->__load();
        return parent::setWebpage($webpage);
    }

    public function setClassificationId($classificationId)
    {
        $this->__load();
        return parent::setClassificationId($classificationId);
    }

    public function setCategotyId($categoryId)
    {
        $this->__load();
        return parent::setCategotyId($categoryId);
    }

    public function setUrlGoogleMaps($urlGoogleMaps)
    {
        $this->__load();
        return parent::setUrlGoogleMaps($urlGoogleMaps);
    }

    public function getNeighborhood()
    {
        $this->__load();
        return parent::getNeighborhood();
    }

    public function getZipcode()
    {
        $this->__load();
        return parent::getZipcode();
    }

    public function setNeighborhood($neighborhood)
    {
        $this->__load();
        return parent::setNeighborhood($neighborhood);
    }

    public function setZipcode($zipcode)
    {
        $this->__load();
        return parent::setZipcode($zipcode);
    }

    public function getAcTime()
    {
        $this->__load();
        return parent::getAcTime();
    }

    public function setAcTime($actime)
    {
        $this->__load();
        return parent::setAcTime($actime);
    }

    public function getPhone()
    {
        $this->__load();
        return parent::getPhone();
    }

    public function setPhone($phone)
    {
        $this->__load();
        return parent::setPhone($phone);
    }

    public function getContact()
    {
        $this->__load();
        return parent::getContact();
    }

    public function setContact($contact)
    {
        $this->__load();
        return parent::setContact($contact);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'extNumber', 'intNumber', 'code', 'name', 'type', 'status', 'openingTime', 'closingTime', 'webpage', 'comments', 'deleted', 'urlGoogleMaps', 'neighborhood', 'zipcode', 'city', 'state', 'country', 'acTime', 'phone', 'contact', 'address', 'controller', 'categoryId', 'classificationId');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}