<?php

namespace MasDistribucion\DefaultDb\Proxies\__CG__;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class DefaultDb_Entities_M3CommerceOrder extends \DefaultDb_Entities_M3CommerceOrder implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getPackages()
    {
        $this->__load();
        return parent::getPackages();
    }

    public function getImages()
    {
        $this->__load();
        return parent::getImages();
    }

    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function getBuyer()
    {
        $this->__load();
        return parent::getBuyer();
    }

    public function getSeller()
    {
        $this->__load();
        return parent::getSeller();
    }

    public function getCreationDate()
    {
        $this->__load();
        return parent::getCreationDate();
    }

    public function getPaymentStatus()
    {
        $this->__load();
        return parent::getPaymentStatus();
    }

    public function getPaymentStatusString($status = false)
    {
        $this->__load();
        return parent::getPaymentStatusString($status);
    }

    public function getShippingStatus()
    {
        $this->__load();
        return parent::getShippingStatus();
    }

    public function getShippingStatusString($status = false)
    {
        $this->__load();
        return parent::getShippingStatusString($status);
    }

    public function getProducts()
    {
        $this->__load();
        return parent::getProducts();
    }

    public function addProduct($product)
    {
        $this->__load();
        return parent::addProduct($product);
    }

    public function getSchedule()
    {
        $this->__load();
        return parent::getSchedule();
    }

    public function getShippingDate()
    {
        $this->__load();
        return parent::getShippingDate();
    }

    public function getComments()
    {
        $this->__load();
        return parent::getComments();
    }

    public function getMonday()
    {
        $this->__load();
        return parent::getMonday();
    }

    public function getTuesday()
    {
        $this->__load();
        return parent::getTuesday();
    }

    public function getWednesday()
    {
        $this->__load();
        return parent::getWednesday();
    }

    public function getThursday()
    {
        $this->__load();
        return parent::getThursday();
    }

    public function getFriday()
    {
        $this->__load();
        return parent::getFriday();
    }

    public function getSaturday()
    {
        $this->__load();
        return parent::getSaturday();
    }

    public function getSunday()
    {
        $this->__load();
        return parent::getSunday();
    }

    public function getRecurrent()
    {
        $this->__load();
        return parent::getRecurrent();
    }

    public function getWeek()
    {
        $this->__load();
        return parent::getWeek();
    }

    public function getOrderStatus()
    {
        $this->__load();
        return parent::getOrderStatus();
    }

    public function getOrderParent()
    {
        $this->__load();
        return parent::getOrderParent();
    }

    public function getPointSeller()
    {
        $this->__load();
        return parent::getPointSeller();
    }

    public function getPointBuyer()
    {
        $this->__load();
        return parent::getPointBuyer();
    }

    public function setId($id)
    {
        $this->__load();
        return parent::setId($id);
    }

    public function setBuyer($buyer)
    {
        $this->__load();
        return parent::setBuyer($buyer);
    }

    public function setSeller($seller)
    {
        $this->__load();
        return parent::setSeller($seller);
    }

    public function setCreationDate($creationDate)
    {
        $this->__load();
        return parent::setCreationDate($creationDate);
    }

    public function setPaymentStatus($paymentStatus)
    {
        $this->__load();
        return parent::setPaymentStatus($paymentStatus);
    }

    public function setShippingStatus($shippingStatus)
    {
        $this->__load();
        return parent::setShippingStatus($shippingStatus);
    }

    public function setProducts($products)
    {
        $this->__load();
        return parent::setProducts($products);
    }

    public function setSchedule($schedule)
    {
        $this->__load();
        return parent::setSchedule($schedule);
    }

    public function setShippingDate($shippingDate)
    {
        $this->__load();
        return parent::setShippingDate($shippingDate);
    }

    public function setImages($images)
    {
        $this->__load();
        return parent::setImages($images);
    }

    public function setComments($comments)
    {
        $this->__load();
        return parent::setComments($comments);
    }

    public function setMonday($monday)
    {
        $this->__load();
        return parent::setMonday($monday);
    }

    public function setTuesday($tuesday)
    {
        $this->__load();
        return parent::setTuesday($tuesday);
    }

    public function setWednesday($wednesday)
    {
        $this->__load();
        return parent::setWednesday($wednesday);
    }

    public function setThursday($thursday)
    {
        $this->__load();
        return parent::setThursday($thursday);
    }

    public function setFriday($friday)
    {
        $this->__load();
        return parent::setFriday($friday);
    }

    public function setSaturday($saturday)
    {
        $this->__load();
        return parent::setSaturday($saturday);
    }

    public function setSunday($sunday)
    {
        $this->__load();
        return parent::setSunday($sunday);
    }

    public function setRecurrent($recurrent)
    {
        $this->__load();
        return parent::setRecurrent($recurrent);
    }

    public function setWeek($week)
    {
        $this->__load();
        return parent::setWeek($week);
    }

    public function setOrderStatus($orderStatus)
    {
        $this->__load();
        return parent::setOrderStatus($orderStatus);
    }

    public function setOrderParent($orderParent)
    {
        $this->__load();
        return parent::setOrderParent($orderParent);
    }

    public function setPointSeller($pointSeller)
    {
        $this->__load();
        return parent::setPointSeller($pointSeller);
    }

    public function setPointBuyer($pointBuyer)
    {
        $this->__load();
        return parent::setPointBuyer($pointBuyer);
    }

    public function getContent()
    {
        $this->__load();
        return parent::getContent();
    }

    public function getContactR()
    {
        $this->__load();
        return parent::getContactR();
    }

    public function getContactS()
    {
        $this->__load();
        return parent::getContactS();
    }

    public function setContent($contentdes)
    {
        $this->__load();
        return parent::setContent($contentdes);
    }

    public function setContactR($contactres)
    {
        $this->__load();
        return parent::setContactR($contactres);
    }

    public function setContactS($contactsend)
    {
        $this->__load();
        return parent::setContactS($contactsend);
    }

    public function getProgramer()
    {
        $this->__load();
        return parent::getProgramer();
    }

    public function setProgramer($programer)
    {
        $this->__load();
        return parent::setProgramer($programer);
    }

    public function getExp()
    {
        $this->__load();
        return parent::getExp();
    }

    public function setExp($stexp)
    {
        $this->__load();
        return parent::setExp($stexp);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'creationDate', 'shippingDate', 'paymentStatus', 'shippingStatus', 'comments', 'monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday', 'recurrent', 'week', 'orderStatus', 'contentdes', 'contactres', 'contactsend', 'programer', 'stexp', 'buyer', 'seller', 'schedule', 'products', 'images', 'packages', 'orderParent', 'pointBuyer', 'pointSeller');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}