<?php

namespace MasDistribucion\DefaultDb\Proxies\__CG__;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class DefaultDb_Entities_CompraCreditos extends \DefaultDb_Entities_CompraCreditos implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function doStuffOnPrePersist()
    {
        $this->__load();
        return parent::doStuffOnPrePersist();
    }

    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function getUsuario()
    {
        $this->__load();
        return parent::getUsuario();
    }

    public function getTipoPago()
    {
        $this->__load();
        return parent::getTipoPago();
    }

    public function getMontoCompra()
    {
        $this->__load();
        return parent::getMontoCompra();
    }

    public function getCreditos()
    {
        $this->__load();
        return parent::getCreditos();
    }

    public function getFecha()
    {
        $this->__load();
        return parent::getFecha();
    }

    public function getPath()
    {
        $this->__load();
        return parent::getPath();
    }

    public function getReferencia()
    {
        $this->__load();
        return parent::getReferencia();
    }

    public function getCuenta()
    {
        $this->__load();
        return parent::getCuenta();
    }

    public function getEstatus()
    {
        $this->__load();
        return parent::getEstatus();
    }

    public function getCliente()
    {
        $this->__load();
        return parent::getCliente();
    }

    public function getTimestamp()
    {
        $this->__load();
        return parent::getTimestamp();
    }

    public function getComentario()
    {
        $this->__load();
        return parent::getComentario();
    }

    public function setId($id)
    {
        $this->__load();
        return parent::setId($id);
    }

    public function setUsuario($usuario)
    {
        $this->__load();
        return parent::setUsuario($usuario);
    }

    public function setTipoPago($tipoPago)
    {
        $this->__load();
        return parent::setTipoPago($tipoPago);
    }

    public function setMontoCompra($montoCompra)
    {
        $this->__load();
        return parent::setMontoCompra($montoCompra);
    }

    public function setCreditos($creditos)
    {
        $this->__load();
        return parent::setCreditos($creditos);
    }

    public function setFecha($fecha)
    {
        $this->__load();
        return parent::setFecha($fecha);
    }

    public function setPath($path)
    {
        $this->__load();
        return parent::setPath($path);
    }

    public function setReferencia($referencia)
    {
        $this->__load();
        return parent::setReferencia($referencia);
    }

    public function setCuenta($cuenta)
    {
        $this->__load();
        return parent::setCuenta($cuenta);
    }

    public function setEstatus($estatus)
    {
        $this->__load();
        return parent::setEstatus($estatus);
    }

    public function setCliente($cliente)
    {
        $this->__load();
        return parent::setCliente($cliente);
    }

    public function setTimestamp($timestamp)
    {
        $this->__load();
        return parent::setTimestamp($timestamp);
    }

    public function setComentario($comentario)
    {
        $this->__load();
        return parent::setComentario($comentario);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'usuario', 'montoCompra', 'creditos', 'fecha', 'path', 'referencia', 'comentario', 'timestamp', 'cliente', 'tipoPago', 'cuenta', 'estatus');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}