<?php

namespace MasDistribucion\DefaultDb\Proxies\__CG__;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class DefaultDb_Entities_Conversion extends \DefaultDb_Entities_Conversion implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        $this->__load();
        return parent::getId();
    }
    
    public function getMoneda()
    {
        $this->__load();
        return parent::getMoneda();
    }
    
    public function getCompra()
    {
        $this->__load();
        return parent::getCompra();
    }
    
    public function getVenta()
    {
        $this->__load();
        return parent::getVenta();
    }
    
    public function getFecha()
    {
        $this->__load();
        return parent::getFecha();
    }
    
    public function getCreditos()
    {
        $this->__load();
        return parent::getCreditos();
    }
    
    public function getClient()
    {
        $this->__load();
        return parent::getClient();
    }

    public function setId($id)
    {
        $this->__load();
        return parent::setId($id);
    }
    
    public function setMoneda($moneda)
    {
        $this->__load();
        return parent::setMoneda($moneda);
    }
    
    public function setCompra($compra)
    {
        $this->__load();
        return parent::setCompra($compra);
    }
    
    public function setVenta($venta)
    {
        $this->__load();
        return parent::setVenta($venta);
    }
    
    public function setFecha($fecha)
    {
        $this->__load();
        return parent::setFecha($fecha);
    }
    
    public function setCreditos($creditos)
    {
        $this->__load();
        return parent::setCreditos($creditos);
    }
    
    public function setClient($client)
    {
        $this->__load();
        return parent::setClient($client);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id','moneda','compra','venta','fecha','creditos','client');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}