<?php

namespace MasDistribucion\DefaultDb\Proxies\__CG__;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class DefaultDb_Entities_AdministracionLogCliente extends \DefaultDb_Entities_AdministracionLogCliente implements \Doctrine\ORM\Proxy\Proxy {

    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;

    public function __construct($entityPersister, $identifier) {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }

    /** @private */
    public function __load() {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized() {
        return $this->__isInitialized__;
    }

    public function getId() {
        $this->__load();
        return parent::getId();
    }

    public function getCompraCreditos() {
        $this->__load();
        return parent::getCompraCreditos();
    }

    public function getTransferenciaCreditos() {
        $this->__load();
        return parent::getTransferenciaCreditos();
    }

    public function getConcepto() {
        $this->__load();
        return parent::getConcepto();
    }

    public function getMonto() {
        $this->__load();
        return parent::getMonto();
    }

    public function getCliente() {
        $this->__load();
        return parent::getCliente();
    }

    public function setId($id) {
        $this->__load();
        return parent::setId($id);
    }

    public function setCompraCreditos($compraCreditos) {
        $this->__load();
        return parent::setCompraCreditos($compraCreditos);
    }

    public function setTransferenciaCreditos($transferenciaCreditos) {
        $this->__load();
        return parent::setTransferenciaCreditos($transferenciaCreditos);
    }

    public function setConcepto($concepto) {
        $this->__load();
        return parent::setConcepto($concepto);
    }

    public function setMonto($monto) {
        $this->__load();
        return parent::setMonto($monto);
    }

    public function setCliente($client) {
        $this->__load();
        return parent::setCliente($client);
    }

    ///////////////////
}
