<?php

namespace MasDistribucion\DefaultDb\Proxies\__CG__;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class DefaultDb_Entities_Invoices extends \DefaultDb_Entities_Invoices implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function getCutDate()
    {
        $this->__load();
        return parent::getCutDate();
    }

    public function getClient()
    {
        $this->__load();
        return parent::getClient();
    }

    public function getStatus()
    {
        $this->__load();
        return parent::getStatus();
    }

    public function getNumOrders()
    {
        $this->__load();
        return parent::getNumOrders();
    }

    public function getPriceTotal()
    {
        $this->__load();
        return parent::getPriceTotal();
    }

    public function getGeneratedInvoice()
    {
        $this->__load();
        return parent::getGeneratedInvoice();
    }

    public function setId($id)
    {
        $this->__load();
        return parent::setId($id);
    }

    public function setCutDate($courtDate)
    {
        $this->__load();
        return parent::setCutDate($courtDate);
    }

    public function setClient($client)
    {
        $this->__load();
        return parent::setClient($client);
    }

    public function setStatus($status)
    {
        $this->__load();
        return parent::setStatus($status);
    }

    public function setNumOrders($numOrders)
    {
        $this->__load();
        return parent::setNumOrders($numOrders);
    }

    public function setPriceTotal($priceTotal)
    {
        $this->__load();
        return parent::setPriceTotal($priceTotal);
    }

    public function setGeneratedInvoice($generatedInvoice)
    {
        $this->__load();
        return parent::setGeneratedInvoice($generatedInvoice);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'cutDate', 'status', 'numOrders', 'priceTotal', 'generatedInvoice', 'client');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}