<?php

namespace MasDistribucion\DefaultDb\Proxies\__CG__;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class DefaultDb_Entities_Cuentas extends \DefaultDb_Entities_Cuentas implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function doStuffOnPrePersist()
    {
        $this->__load();
        return parent::doStuffOnPrePersist();
    }

    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function getNumeroCuenta()
    {
        $this->__load();
        return parent::getNumeroCuenta();
    }

    public function getCuenta()
    {
        $this->__load();
        return parent::getCuenta();
    }

    public function getClabeInterbancaria()
    {
        $this->__load();
        return parent::getClabeInterbancaria();
    }

    public function getMoneda()
    {
        $this->__load();
        return parent::getMoneda();
    }

    public function getName()
    {
        $this->__load();
        return parent::getName();
    }

    public function getTipoOperador()
    {
        $this->__load();
        return parent::getTipoOperador();
    }

    public function getPais()
    {
        $this->__load();
        return parent::getPais();
    }

    public function getEstado()
    {
        $this->__load();
        return parent::getEstado();
    }

    public function getCliente()
    {
        $this->__load();
        return parent::getCliente();
    }

    public function getTimestamp()
    {
        $this->__load();
        return parent::getTimestamp();
    }

    public function getBanco()
    {
        $this->__load();
        return parent::getBanco();
    }

    public function setId($id)
    {
        $this->__load();
        return parent::setId($id);
    }

    public function setNumeroCuenta($numeroCuenta)
    {
        $this->__load();
        return parent::setNumeroCuenta($numeroCuenta);
    }

    public function setCuenta($cuenta)
    {
        $this->__load();
        return parent::setCuenta($cuenta);
    }

    public function setClabeInterbancaria($clabeInterbancaria)
    {
        $this->__load();
        return parent::setClabeInterbancaria($clabeInterbancaria);
    }

    public function setMoneda($moneda)
    {
        $this->__load();
        return parent::setMoneda($moneda);
    }

    public function setName($name)
    {
        $this->__load();
        return parent::setName($name);
    }

    public function setTipoOperador($tipoOperador)
    {
        $this->__load();
        return parent::setTipoOperador($tipoOperador);
    }

    public function setPais($pais)
    {
        $this->__load();
        return parent::setPais($pais);
    }

    public function setEstado($estado)
    {
        $this->__load();
        return parent::setEstado($estado);
    }

    public function setCliente($cliente)
    {
        $this->__load();
        return parent::setCliente($cliente);
    }

    public function setTimestamp($timestamp)
    {
        $this->__load();
        return parent::setTimestamp($timestamp);
    }

    public function setBanco($banco)
    {
        $this->__load();
        return parent::setBanco($banco);
    }

    public function setTipoPago($tipoPago)
    {
        $this->__load();
        return parent::setTipoPago($tipoPago);
    }

    public function getTipoPago()
    {
        $this->__load();
        return parent::getTipoPago();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'numeroCuenta', 'cuenta', 'clabeInterbancaria', 'tipoOperador', 'estado', 'cliente', 'timestamp', 'moneda', 'pais', 'banco', 'tipoPago');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}