<?php

namespace MasDistribucion\DefaultDb\Proxies\__CG__;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class DefaultDb_Entities_Transactions extends \DefaultDb_Entities_Transactions implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        $this->__load();
        return parent::getId();
    }

    public function getTransactionId()
    {
        $this->__load();
        return parent::getTransactionId();
    }

    public function getStatus()
    {
        $this->__load();
        return parent::getStatus();
    }

    public function getTransactionType()
    {
        $this->__load();
        return parent::getTransactionType();
    }

    public function getStatusPoint()
    {
        $this->__load();
        return parent::getStatusPoint();
    }

    public function setId($id)
    {
        $this->__load();
        return parent::setId($id);
    }

    public function setTransactionId($transactionId)
    {
        $this->__load();
        return parent::setTransactionId($transactionId);
    }

    public function setStatus($status)
    {
        $this->__load();
        return parent::setStatus($status);
    }

    public function setTransactionType($transactionType)
    {
        $this->__load();
        return parent::setTransactionType($transactionType);
    }

    public function setStatusPoint($statusPoint)
    {
        $this->__load();
        return parent::setStatusPoint($statusPoint);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'transactionId', 'status', 'transactionType', 'statusPoint');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}