<?php

namespace MasDistribucion\DefaultDb\Proxies\__CG__;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class DefaultDb_Entities_Route extends \DefaultDb_Entities_Route implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getFactor()
    {
        $this->__load();
        return parent::getFactor();
    }

    public function setFactor($factor)
    {
        $this->__load();
        return parent::setFactor($factor);
    }

    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function getName()
    {
        $this->__load();
        return parent::getName();
    }

    public function getStatus()
    {
        $this->__load();
        return parent::getStatus();
    }

    public function getCapacity()
    {
        $this->__load();
        return parent::getCapacity();
    }

    public function setId($id)
    {
        $this->__load();
        return parent::setId($id);
    }

    public function getCode()
    {
        $this->__load();
        return parent::getCode();
    }

    public function setCode($code)
    {
        $this->__load();
        return parent::setCode($code);
    }

    public function setName($name)
    {
        $this->__load();
        return parent::setName($name);
    }

    public function setStatus($status)
    {
        $this->__load();
        return parent::setStatus($status);
    }

    public function setCapacity($capacity)
    {
        $this->__load();
        return parent::setCapacity($capacity);
    }

    public function getSchedules()
    {
        $this->__load();
        return parent::getSchedules();
    }

    public function setClose($close)
    {
        $this->__load();
        return parent::setClose($close);
    }

    public function toggleClose()
    {
        $this->__load();
        return parent::toggleClose();
    }

    public function getController()
    {
        $this->__load();
        return parent::getController();
    }

    public function setController($controller)
    {
        $this->__load();
        return parent::setController($controller);
    }

    public function getFranchisee()
    {
        $this->__load();
        return parent::getFranchisee();
    }

    public function setFranchisee($franchisee)
    {
        $this->__load();
        return parent::setFranchisee($franchisee);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'code', 'name', 'status', 'capacity', 'factor', 'close', 'schedules', 'zone', 'controller', 'franchisee');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}